version: '3.9'
name: hummingbot-core

services:
  db:
    image: postgres:13
    container_name: hbot-db
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - hbotnet

  gateway:
    image: hummingbot/gateway:latest
    container_name: hbot-gateway
    ports:
      - 8080:8080
      - 15888:15888
    volumes:
      - type: volume
        source: hbot-gateway-conf
        target: /conf
      - type: volume
        source: hbot-gateway-logs
        target: /logs
      - type: volume
        source: hbot-gateway-certs
        target: /certs
    environment:
      - GATEWAY_PASSPHRASE=123
      - PORT=15888
    networks:
      - hbotnet

volumes:
  hbot-gateway-certs:
    name: hbot-gateway-certs
    driver: local
    driver_opts: {}
  hbot-gateway-conf:
    name: hbot-gateway-conf
    driver: local
    driver_opts: {}
  hbot-gateway-logs:
    name: hbot-gateway-logs
    driver: local
    driver_opts: {}

  db-data:
    name: db-data
    driver: local
    driver_opts: {}

networks:
  hbotnet:
    name: "hbotnet"
    driver: bridge
