version: '3.9'
name: hummingbot-core

services:
  db:
    image: ${DB_IMAGE:-postgres:13}
    container_name: hbot-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - hbot-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - hbotnet
    profiles: ['db', 'all']

  gateway:
    image: hummingbot/gateway:latest
    container_name: hbot-gateway
    restart: unless-stopped
    ports:
      - ${GW_DOCS_PORT:-8080}:8080
      - ${GW_PORT:-15888}:15888
    volumes:
      - type: volume
        source: hbot-gateway-conf
        target: /usr/src/app/conf
      - type: volume
        source: hbot-gateway-logs
        target: /usr/src/app/logs
      - type: volume
        source: hbot-gateway-certs
        target: /usr/src/app/certs
    environment:
      - GATEWAY_PASSPHRASE=${GW_PASSPHRASE:-123}
    networks:
      - hbotnet
    profiles: ['gateway', 'all']

  streanlitapp:
    image: ${STREAMLIT_APP_IMAGE:-"hummingbot/streamlit-app:latest"}
    container_name: streanlit-app
    restart: unless-stopped
    ports:
      - ${STREAMLIT_APP_PORT:-8501}:8501
    networks:
      hbotnet:
        aliases:
        - streamlit-app.local
    profiles: ['analysis', 'all']

  emqx1:
    image: ${MQTT_EMQX_IMAGE:-emqx:5}
    restart: unless-stopped
    container_name: hbot-emqx-1
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.local]
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - hbot-emqx-data:/opt/emqx/data
      - hbot-emqx-log:/opt/emqx/log
      - hbot-emqx-etc:/opt/emqx/etc
    ports:
      - "1883:1883"  # mqtt:tcp
      - "8883:8883"  # mqtt:tcp:ssl
      - "8083:8083"  # mqtt:ws
      - "8084:8084"  # mqtt:ws:ssl
      - "8081:8081"  # http:management
      - "18083:18083"  # http:dashboard
      - "61613:61613"  # web-stomp gateway
    networks:
      hbotnet:
        aliases:
        - node1.emqx.local
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    profiles: ['mqtt', 'all']

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: hbot-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus:/etc/prometheus
      - hbot-prometheus-storage:/prometheus
    networks:
      hbotnet:
        aliases:
        - prometheus.local
    profiles: ['obs', 'all']

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:9.3.2}
    container_name: hbot-grafana
    restart: unless-stopped
    ports:
      - ${GRAFANA_DASHBOARD_PORT:-3000}:3000
    volumes:
      - hbot-grafana-storage:/var/lib/grafana
    networks:
      hbotnet:
        aliases:
        - grafana.local
    profiles: ['obs', 'all']

  tradingview-mqtt-bridge:
    image: ${TV_BRIDGE_IMAGE:-klpanagi/tradingview-mqtt-bridge:latest}
    container_name: tradingview-mqtt-bridge
    restart: unless-stopped
    depends_on:
      emqx1:
        condition: service_healthy
        restart: true
    ports:
      - '80:8080'
    environment:
      - SEC_KEY=${TV_BRIDGE_SEC_KEY:-123123}
      - MQTT_HOST=node1.emqx.local
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_TOPIC=${TV_BRIDGE_MQTT_TOPIC:-tradingview/alerts}
    command: [
      "uvicorn",
      "app:app",
      "--workers", "4",
      "--host", "0.0.0.0",
      "--port", "8080",
      '--root-path', '/']
    networks:
      hbotnet:
        aliases:
        - tv-mqtt-bridge.local
    profiles: ['tradingview', 'all']

volumes:
  hbot-gateway-certs:
    name: hbot-gateway-certs
    driver: local
    driver_opts: {}
  hbot-gateway-conf:
    name: hbot-gateway-conf
    driver: local
    driver_opts: {}
  hbot-gateway-logs:
    name: hbot-gateway-logs
    driver: local
    driver_opts: {}

  hbot-db-data:
    name: hbot-db-data
    driver: local
    driver_opts: {}

  hbot-emqx-data:
    name: hbot-emqx-data
    driver: local
    driver_opts: {}
  hbot-emqx-log:
    name: hbot-emqx-log
    driver: local
    driver_opts: {}
  hbot-emqx-etc:
    name: hbot-emqx-etc
    driver: local
    driver_opts: {}

  hbot-prometheus-storage: {}
  hbot-grafana-storage: {}

networks:
  hbotnet:
    name: "hbotnet"
    driver: bridge
