services:
  hbot:
    container_name: hbot-${HBOT_ID}
    image: ${HBOT_IMAGE}
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      # - ./scripts:/home/hummingbot/scripts
      # - ./controllers:/home/hummingbot/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    # environment:
      # - CONFIG_PASSWORD="123"
      # - CONFIG_FILE_NAME=simple_pmm_example.py
      # - SCRIPT_CONFIG=conf_simple_pmm_example.yaml
