version: '3.9'
name: hummingbot

services:
  hbot:
    container_name: hbot-${HBOT_ID}
    image: ${HBOT_IMAGE:-"hummingbot/hummingbot:latest"}
    volumes:
      - ${HOST_DOCKER}:/var/run/docker.sock
      - hbot-data:/data
      - hbot-conf:/conf
      - hbot-logs:/logs
      - hbot-scripts:/scripts
      - hbot-pmmscripts:/pmm_scripts
      - hbot-gateway-certs:/home/hummingbot/certs
    environment:
      - CONFIG_PASSWORD=${HBOT_PSK}
      - CONFIG_FILE_NAME=${HBOT_FILE}
      - CERTS_FOLDER="/home/hummingbot/certs"
      - GATEWAY_CONF_FOLDER="/gateway-conf"
      - GATEWAY_LOGS_FOLDER="/logs"
    network_mode: "host"
    # networks:
    #   - hbotnet
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    mem_limit: ${MEM_LIMIT:-1000}m
    mem_reservation: ${MEM_RESERVATION:-300}m
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: 5

volumes:
  hbot-data:
    name: hbot-${HBOT_ID}-data
    driver: local
    driver_opts: {}
  hbot-conf:
    name: hbot-${HBOT_ID}-conf
    driver: local
    driver_opts: {}
  hbot-logs:
    name: hbot-${HBOT_ID}-logs
    driver: local
    driver_opts: {}
  hbot-scripts:
    name: hbot-${HBOT_ID}-scripts
    driver: local
    driver_opts: {}
  hbot-pmmscripts:
    name: hbot-${HBOT_ID}-pmmscripts
    driver: local
    driver_opts: {}

  hbot-gateway-certs:
    external: true

networks:
  hbotnet:
    name: "hbotnet"
    driver: bridge
    external: true
