version: '3.9'
name: hummingbot

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  hbot:
    container_name: hbot-${HBOT_ID}
    image: ${HBOT_IMAGE:-"hummingbot/hummingbot:latest"}
    volumes:
      - ${HOST_DOCKER}:/var/run/docker.sock
      - hbot-data:/data
      - hbot-conf:/conf
      - hbot-logs:/logs
      - hbot-scripts:/scripts
      - hbot-pmmscripts:/pmm_scripts
    environment:
      - HBOT_UID=${HBOT_ID}
      - CONFIG_PASSWORD=${HBOT_PSK}
      - CONFIG_FILE_NAME=${HBOT_FILE}
      - HBOT_HAS_TUI=${HBOT_TUI}
      - CERTS_FOLDER="/home/hummingbot/.hummingbot-gateway/certs/"
      - GATEWAY_CONF_FOLDER="/gateway-conf/"
      - GATEWAY_LOGS_FOLDER="/logs"
    # network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      # - hostnet
      - hbotnet
    mem_limit: ${MEM_LIMIT:-1000}m
    mem_reservation: ${MEM_RESERVATION:-100}m
    logging:
      options:
        max-size: "100m"
        max-file: 5

volumes:
  hbot-data:
    name: hbot-${HBOT_ID}-data
    driver: local
    driver_opts: {}
  hbot-conf:
    name: hbot-${HBOT_ID}-conf
    driver: local
    driver_opts: {}
  hbot-logs:
    name: hbot-${HBOT_ID}-logs
    driver: local
    driver_opts: {}
  hbot-scripts:
    name: hbot-${HBOT_ID}-scripts
    driver: local
    driver_opts: {}
  hbot-pmmscripts:
    name: hbot-${HBOT_ID}-pmmscripts
    driver: local
    driver_opts: {}

  db-data:
    name: db-data
    driver: local
    driver_opts: {}


networks:
  hostnet:
    external: true
    name: host
  nonet:
    external: true
    name: none
  hbotnet: {}
